let inputWidth;
let inputHeight;
inputWidth = prompt("Enter the width");
inputHeight = prompt("Enter the height");
let a = inputWidth;
let b = inputHeight;
let width = parseInt(inputWidth);
let height = parseInt(inputHeight);
let area = width * height;
document.write("The area is: " + area);
var ketqua = area;
// document.getElementById("ketqua").innerHTML = area;